env:
  name: dev
  des: 开发环境
  list:
    list1: [1,2,3,4]
    list2: &list
      - Apple
      - Banana
      - Pair
  object-list1:
    -
      id: 1
      name: Ilirus
    -
      id: 2
      name: Erina
  object-list2: [{id: 1, name: ilirus},{id: 2, name: erina}]
  list-copy <<: *list
  map:
    key: value
    key2: value2
logging:
  config: classpath:dev/log4j2.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      idle-timeout: 300000
      connection-timeout: 5000

mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/**/*Mapper.xml
  check-config-location: true

mybatis-plus:
  mapper-locations: classpath:/mybatis/**/*Mapper.xml
  type-aliases-package: com.ilirus.springbootdemo.model.po
  global-config:
    db-config:
      id-type: auto
      insert-strategy: not_null
      update-strategy: not_null
